// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs9Ep_YfCoudxiTJ79ttfUxm2dL0zKwfI',
    appId: '1:995409018813:web:c80a9c4e36e4fa332a5cd4',
    messagingSenderId: '995409018813',
    projectId: 'chat-app-dfcf6',
    authDomain: 'chat-app-dfcf6.firebaseapp.com',
    storageBucket: 'chat-app-dfcf6.appspot.com',
    measurementId: 'G-EKKQ60R5M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDICDIn4XMCi8HpE0QHMWV5jj0BkO36AG0',
    appId: '1:995409018813:android:78c1b25c13401ca42a5cd4',
    messagingSenderId: '995409018813',
    projectId: 'chat-app-dfcf6',
    storageBucket: 'chat-app-dfcf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5rRHB9P1hjokQbLh2B-Mhlwps85L4OOg',
    appId: '1:995409018813:ios:b3c7d4bb249a202f2a5cd4',
    messagingSenderId: '995409018813',
    projectId: 'chat-app-dfcf6',
    storageBucket: 'chat-app-dfcf6.appspot.com',
    iosClientId: '995409018813-p72c11ehe8hgdegienpfggq51hqrvelj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5rRHB9P1hjokQbLh2B-Mhlwps85L4OOg',
    appId: '1:995409018813:ios:b3c7d4bb249a202f2a5cd4',
    messagingSenderId: '995409018813',
    projectId: 'chat-app-dfcf6',
    storageBucket: 'chat-app-dfcf6.appspot.com',
    iosClientId: '995409018813-p72c11ehe8hgdegienpfggq51hqrvelj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
